services:
  monitoramento:
    image: ghcr.io/sidneyjfg/monitoramento_automatico_full:latest  # Substitua pelo caminho da sua imagem no GitHub
    container_name: monitoramento_automatico_notasFull
    restart: unless-stopped
    env_file: 
      - .env  # Carrega as variáveis do arquivo .env
    environment:
      # Utilizando as variáveis de ambiente definidas no .env
      - CLIENTE_ARCELOR_USER=${ARCELOR_USER}
      - CLIENTE_ARCELOR_SERVER=${ARCELOR_SERVER}
      - CLIENTE_ARCELOR_PORT=${ARCELOR_PORT}
      - CLIENTE_ARCELOR_PASSWORD=${ARCELOR_PASS}
      - CLIENTE_ARCELOR_PATH=/tmp
      
      - CLIENTE_TRES_USER=${TRES_USER}
      - CLIENTE_TRES_SERVER=${TRES_SERVER}
      - CLIENTE_TRES_PORT=${TRES_PORT}
      - CLIENTE_TRES_PASSWORD=${TRES_PASS}
      - CLIENTE_TRES_PATH=/tmp
      
      - CLIENTE_LORENZETTI_USER=${LORENZETTI_USER}
      - CLIENTE_LORENZETTI_SERVER=${LORENZETTI_SERVER}
      - CLIENTE_LORENZETTI_PORT=${LORENZETTI_PORT}
      - CLIENTE_LORENZETTI_PASSWORD=${LORENZETTI_PASS}
      - CLIENTE_LORENZETTI_PATH=/tmp
      
      - CLIENTE_MUELLER_USER=${MUELLER_USER}
      - CLIENTE_MUELLER_SERVER=${MUELLER_SERVER}
      - CLIENTE_MUELLER_PORT=${MUELLER_PORT}
      - CLIENTE_MUELLER_PASSWORD=${MUELLER_PASS}
      - CLIENTE_MUELLER_PATH=/tmp
      - CLIENTE_MUELLER_ARQUIVOS_ESPECIAIS=FG,EL

      - CLIENTE_MUFFATO_USER=${MUFFATO_USER}
      - CLIENTE_MUFFATO_SERVER=${MUFFATO_SERVER}
      - CLIENTE_MUFFATO_PORT=${MUFFATO_PORT}
      - CLIENTE_MUFFATO_PASSWORD=${MUFFATO_PASS}
      - CLIENTE_MUFFATO_PATH=/tmp
      - CLIENTE_MUFFATO_ARQUIVOS_ESPECIAIS=PR,SP

      - CLIENTE_PIRAHY_USER=${PIRAHY_USER}
      - CLIENTE_PIRAHY_SERVER=${PIRAHY_SERVER}
      - CLIENTE_PIRAHY_PORT=${PIRAHY_PORT}
      - CLIENTE_PIRAHY_PASSWORD=${PIRAHY_PASS}
      - CLIENTE_PIRAHY_PATH=/tmp

      - EXECUTAR_IMPORTA_NOTAS=false  # Use 'false' para testes, 'true' para produção

      # Variável do diretório base
      - BASE_DIR=${BASE_DIR}
      
      - PORT=3000
      - CRON_SCHEDULE="0 * * * *"
      - TZ=America/Sao_Paulo

    volumes:
      - "./:/app"
      - "${BASE_DIR}:${BASE_DIR}"  # Monta o diretório base
    ports:
      - "3001:3000"
    command: python /app/script.py
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
