services:
  monitoramento:
    image: ghcr.io/sidneyjfg/monitoramento_automatico_full:latest  # Substitua pelo caminho da sua imagem no GitHub
    container_name: monitoramento_automatico_notasFull
    restart: unless-stopped
    env_file: 
      - .env  # Carrega as variáveis do arquivo .env
    environment:
      # Utilizando as variáveis de ambiente definidas no .env
      - CLIENTE_ARCELOR_USER=${ARCELOR_USER}
      - CLIENTE_ARCELOR_SERVER=${ARCELOR_SERVER}
      - CLIENTE_ARCELOR_PORT=${ARCELOR_PORT}
      - CLIENTE_ARCELOR_PASSWORD=${ARCELOR_PASS}
      - CLIENTE_ARCELOR_PATH=/tmp
      
      - CLIENTE_TRES_USER=${TRES_USER}
      - CLIENTE_TRES_SERVER=${TRES_SERVER}
      - CLIENTE_TRES_PORT=${TRES_PORT}
      - CLIENTE_TRES_PASSWORD=${TRES_PASS}
      - CLIENTE_TRES_PATH=/tmp
      
      - CLIENTE_LORENZETTI_USER=${LORENZETTI_USER}
      - CLIENTE_LORENZETTI_SERVER=${LORENZETTI_SERVER}
      - CLIENTE_LORENZETTI_PORT=${LORENZETTI_PORT}
      - CLIENTE_LORENZETTI_PASSWORD=${LORENZETTI_PASS}
      - CLIENTE_LORENZETTI_PATH=/tmp
      
      - CLIENTE_MUELLER_USER=${MUELLER_USER}
      - CLIENTE_MUELLER_SERVER=${MUELLER_SERVER}
      - CLIENTE_MUELLER_PORT=${MUELLER_PORT}
      - CLIENTE_MUELLER_PASSWORD=${MUELLER_PASS}
      - CLIENTE_MUELLER_PATH=/tmp
      - CLIENTE_MUELLER_ARQUIVOS_ESPECIAIS=FG,EL

      - CLIENTE_MUFF
